import { NewExercise } from './schema'

export const WORKOUT_EXERCISES: NewExercise[] = [
  // DAY A — Back, Arms, Rear Delts + Abs
  {
    name: 'Chest-Supported Machine Row',
    day: 'A',
    order: 1,
    sets: 4,
    repRangeMin: 8,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Neutral-Grip Lat Pulldown',
    day: 'A',
    order: 2,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Single-Arm Cable Row',
    day: 'A',
    order: 3,
    sets: 3,
    repRangeMin: 12,
    repRangeMax: 12,
    isUnilateral: true,
    notes: 'per side',
  },
  {
    name: 'Rear Delt Fly',
    day: 'A',
    order: 4,
    sets: 3,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
  },
  {
    name: 'Straight-Arm Cable Pulldown',
    day: 'A',
    order: 5,
    sets: 3,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
  },
  {
    name: 'Incline Dumbbell Curl',
    day: 'A',
    order: 6,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Rope Triceps Pushdown',
    day: 'A',
    order: 7,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Standing Calf Raise',
    day: 'A',
    order: 8,
    sets: 4,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
  },
  {
    name: 'Hanging Leg Raises',
    day: 'A',
    order: 9,
    sets: 3,
    repRangeMin: 8,
    repRangeMax: 12,
    isUnilateral: false,
    notes: 'AB FINISHER',
  },

  // DAY B — Glutes, Chest, Shoulders, Arms + Abs
  {
    name: 'Bulgarian Split Squat',
    day: 'B',
    order: 1,
    sets: 4,
    repRangeMin: 8,
    repRangeMax: 8,
    isUnilateral: true,
    notes: 'per leg',
  },
  {
    name: 'Dumbbell Step-Back Lunge',
    day: 'B',
    order: 2,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 10,
    isUnilateral: true,
    notes: 'per leg',
  },
  {
    name: 'Seated or Lying Leg Curl',
    day: 'B',
    order: 3,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Dumbbell Chest Press',
    day: 'B',
    order: 4,
    sets: 3,
    repRangeMin: 8,
    repRangeMax: 10,
    isUnilateral: false,
  },
  {
    name: 'Seated Dumbbell Lateral Raise',
    day: 'B',
    order: 5,
    sets: 3,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
  },
  {
    name: 'Face Pulls or Reverse Pec Deck',
    day: 'B',
    order: 6,
    sets: 3,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
  },
  {
    name: 'Preacher Curl',
    day: 'B',
    order: 7,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Overhead Rope Triceps Extension',
    day: 'B',
    order: 8,
    sets: 3,
    repRangeMin: 10,
    repRangeMax: 12,
    isUnilateral: false,
  },
  {
    name: 'Seated Calf Raise',
    day: 'B',
    order: 9,
    sets: 4,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
  },
  {
    name: 'Machine Crunch',
    day: 'B',
    order: 10,
    sets: 3,
    repRangeMin: 12,
    repRangeMax: 15,
    isUnilateral: false,
    notes: 'AB FINISHER',
  },
]
